sudo: false
language: go
go:
  - 1.9.2
go_import_path: github.com/cofyc/socks2http
install: true
script:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only
  - go test -timeout 5m github.com/cofyc/socks2http/...
  - go install github.com/cofyc/socks2http/cmd/socks2http
